# Generated by Django 3.2 on 2022-12-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
